# Generated by Django 4.2.5 on 2025-02-05 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('investment_id', models.AutoField(primary_key=True, serialize=False)),
                ('investment_type', models.CharField(max_length=100)),
                ('risk_level', models.IntegerField()),
                ('min_investment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_return', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'investments',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('risk_profile', models.CharField(max_length=50)),
                ('income_monthly', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expenses_monthly', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentage_save', models.DecimalField(decimal_places=2, max_digits=5)),
                ('age', models.IntegerField()),
                ('investment_experience', models.IntegerField()),
                ('cluster', models.IntegerField(default=-1)),
                ('total_investment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'db_table': 'financing_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
            options={
                'db_table': 'user_recommendations',
            },
        ),
        migrations.CreateModel(
            name='UserInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
            options={
                'db_table': 'user_investments',
            },
        ),
    ]
