# Generated by Django 4.2.5 on 2025-02-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userprofile_income_monthly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='percentage_save',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
